package com.example.myfinance

import android.content.Context
import android.os.Bundle
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp
import org.json.JSONArray
import org.json.JSONObject
import java.text.SimpleDateFormat
import java.util.*

data class Account(val id: Long, val name: String, val type: String, val balance: Double = 0.0, val rate: Double = 0.0, val capitalization: Boolean = false)
data class Operation(val id: Long, val amount: Double, val category: String, val comment: String, val income: Boolean, val accountId: Long, val mandatory: Boolean = false)
data class ForecastItem(val id: Long, val name: String, val amount: Double, val income: Boolean, val date: Long, val recurrence: String = "Разово", val accountId: Long = 0L)

data class CalendarEvent(val date: Long, val title: String, val amount: Double, val income: Boolean)

private const val PREFS_NAME = "my_finance_data"
private const val OPERATIONS_KEY = "operations"
private const val ACCOUNTS_KEY = "accounts"
private const val FORECAST_KEY = "forecast"

val IncomeColor = Color(0xFF2E7D32)
val IncomeContainer = Color(0xFFE8F5E9)
val ExpenseColor = Color(0xFFC62828)
val ExpenseContainer = Color(0xFFFFEBEE)

fun money(v: Double) = String.format(Locale.getDefault(), "%.2f", v)
fun formatDate(t: Long) = SimpleDateFormat("dd.MM.yyyy", Locale.getDefault()).format(Date(t))
fun parseDate(s: String): Long? = runCatching { SimpleDateFormat("dd.MM.yyyy", Locale.getDefault()).parse(s)?.time }.getOrNull()

fun saveData(c: Context, accounts: List<Account>, operations: List<Operation>, forecast: List<ForecastItem>) {
    val p = c.getSharedPreferences(PREFS_NAME, Context.MODE_PRIVATE)
    val a = JSONArray(); accounts.forEach { a.put(JSONObject().apply { put("id",it.id);put("name",it.name);put("type",it.type);put("balance",it.balance);put("rate",it.rate);put("capitalization",it.capitalization) }) }
    val o = JSONArray(); operations.forEach { o.put(JSONObject().apply { put("id",it.id);put("amount",it.amount);put("category",it.category);put("comment",it.comment);put("income",it.income);put("accountId",it.accountId);put("mandatory",it.mandatory) }) }
    val f = JSONArray(); forecast.forEach { f.put(JSONObject().apply { put("id",it.id);put("name",it.name);put("amount",it.amount);put("income",it.income);put("date",it.date);put("recurrence",it.recurrence);put("accountId",it.accountId) }) }
    p.edit().putString(ACCOUNTS_KEY,a.toString()).putString(OPERATIONS_KEY,o.toString()).putString(FORECAST_KEY,f.toString()).apply()
}
fun loadAccounts(c: Context): List<Account> = runCatching { JSONArray(c.getSharedPreferences(PREFS_NAME,0).getString(ACCOUNTS_KEY,"[]")).let { j -> buildList { for(i in 0 until j.length()){val x=j.getJSONObject(i);add(Account(x.getLong("id"),x.getString("name"),x.getString("type"),x.optDouble("balance"),x.optDouble("rate"),x.optBoolean("capitalization"))) } } } }.getOrDefault(emptyList())
fun loadOperations(c: Context, accounts: List<Account>): List<Operation> = runCatching { JSONArray(c.getSharedPreferences(PREFS_NAME,0).getString(OPERATIONS_KEY,"[]")).let { j -> buildList { for(i in 0 until j.length()){val x=j.getJSONObject(i);add(Operation(x.getLong("id"),x.getDouble("amount"),x.getString("category"),x.optString("comment"),x.optBoolean("income"),x.optLong("accountId",accounts.firstOrNull()?.id?:0L),x.optBoolean("mandatory",false))) } } } }.getOrDefault(emptyList())
fun loadForecast(c: Context): List<ForecastItem> = runCatching { JSONArray(c.getSharedPreferences(PREFS_NAME,0).getString(FORECAST_KEY,"[]")).let { j -> buildList { for(i in 0 until j.length()){val x=j.getJSONObject(i);add(ForecastItem(x.getLong("id"),x.getString("name"),x.getDouble("amount"),x.optBoolean("income"),x.getLong("date"),x.optString("recurrence","Разово"),x.optLong("accountId",0L))) } } } }.getOrDefault(emptyList())
fun balances(accounts: List<Account>, operations: List<Operation>) = accounts.associate { a -> a.id to (a.balance + operations.filter { it.accountId==a.id }.sumOf { if(it.income) it.amount else -it.amount }) }

class MainActivity : ComponentActivity() { override fun onCreate(s: Bundle?) { super.onCreate(s); setContent { MaterialTheme { FinanceApp(this) } } } }

@Composable fun FinanceApp(c: Context) {
    var accounts by remember { mutableStateOf(loadAccounts(c)) }; var operations by remember { mutableStateOf(loadOperations(c,accounts)) }; var forecast by remember { mutableStateOf(loadForecast(c)) }; var tab by remember { mutableStateOf(0) }
    fun save(a: List<Account> = accounts,o: List<Operation> = operations,f: List<ForecastItem> = forecast){accounts=a;operations=o;forecast=f;saveData(c,a,o,f)}
    if(accounts.isEmpty()){accounts=listOf(Account(1,"Основной счёт","card"));save(a=accounts)}
    Scaffold(bottomBar={NavigationBar{listOf("Главная","Операции","Календарь","Статистика","Ещё").forEachIndexed{i,t->NavigationBarItem(tab==i,{tab=i},{Icon(when(i){0->Icons.Default.Home;1->Icons.Default.List;2->Icons.Default.DateRange;3->Icons.Default.PieChart;else->Icons.Default.MoreHoriz},t)},label={Text(t)})}}}){p->when(tab){0->HomeScreen(accounts,operations,Modifier.padding(p));1->OperationsScreen(operations,accounts,Modifier.padding(p));2->CalendarScreen(operations,forecast,Modifier.padding(p));3->StatisticsScreen(operations,accounts,Modifier.padding(p));4->MoreScreen(forecast,accounts,{save(f=it)},{save(o=operations+it)},Modifier.padding(p))}}
}

@Composable fun HomeScreen(accounts:List<Account>,operations:List<Operation>,modifier:Modifier=Modifier){val b=balances(accounts,operations);val inc=operations.filter{it.income}.sumOf{it.amount};val exp=operations.filter{!it.income}.sumOf{it.amount};Column(modifier.fillMaxSize().padding(16.dp).verticalScroll(rememberScrollState())){Text("Мои финансы",style=MaterialTheme.typography.headlineMedium);Spacer(Modifier.height(16.dp));Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.spacedBy(12.dp)){SummaryBlock("Доходы",inc,IncomeContainer,IncomeColor,Modifier.weight(1f));SummaryBlock("Расходы",exp,ExpenseContainer,ExpenseColor,Modifier.weight(1f))};Spacer(Modifier.height(20.dp));Text("Счета",style=MaterialTheme.typography.titleLarge);accounts.forEach{a->Card(Modifier.fillMaxWidth().padding(vertical=4.dp)){Column(Modifier.padding(16.dp)){Text(a.name,style=MaterialTheme.typography.titleMedium);Text(money(b[a.id]?:0.0));if(a.type=="deposit"){Text("Ставка: ${a.rate}%");Text(if(a.capitalization)"Капитализация: да" else "Капитализация: нет")}}}};Spacer(Modifier.height(16.dp));Text("Последние операции",style=MaterialTheme.typography.titleLarge);operations.sortedByDescending{it.id}.take(5).forEach{OperationBlock(it)}}}
@Composable fun SummaryBlock(title:String,value:Double,bg:Color,fg:Color,modifier:Modifier=Modifier){Card(colors=CardDefaults.cardColors(bg),modifier=modifier){Column(Modifier.padding(16.dp)){Text(title,color=fg);Text(money(value),style=MaterialTheme.typography.titleLarge,color=fg)}}}
@Composable fun OperationBlock(o:Operation){val bg=if(o.income)IncomeContainer else ExpenseContainer;val fg=if(o.income)IncomeColor else ExpenseColor;Card(colors=CardDefaults.cardColors(bg),Modifier.fillMaxWidth().padding(vertical=4.dp)){Row(Modifier.fillMaxWidth().padding(12.dp),horizontalArrangement=Arrangement.SpaceBetween){Column(Modifier.weight(1f)){Text(o.category,color=fg);if(o.comment.isNotBlank())Text(o.comment);if(!o.income&&o.mandatory)Text("Обязательный",color=fg)};Text("${if(o.income)"+" else "-"}${money(o.amount)}",color=fg)}}}

@Composable fun OperationsScreen(operations:List<Operation>,accounts:List<Account>,modifier:Modifier=Modifier){Column(modifier.fillMaxSize()){Text("Операции",style=MaterialTheme.typography.headlineMedium,modifier=Modifier.padding(16.dp));LazyColumn(contentPadding=PaddingValues(horizontal=16.dp)){items(operations.sortedByDescending{it.id},key={it.id}){o->OperationBlock(o);Text("Счёт: ${accounts.firstOrNull{a->a.id==o.accountId}?.name?:"Счёт"}",modifier=Modifier.padding(bottom=6.dp))}}}}
@Composable fun CalendarScreen(operations:List<Operation>,forecast:List<ForecastItem>,modifier:Modifier=Modifier){val s=System.currentTimeMillis()-30L*86400000;val e=System.currentTimeMillis()+30L*86400000;val ev=(operations.filter{it.id in s..e}.map{CalendarEvent(it.id,if(it.income)"Доход" else "Расход",it.amount,it.income)}+forecast.filter{it.date in s..e}.map{CalendarEvent(it.date,it.name,it.amount,it.income)}).sortedBy{it.date};Column(modifier.fillMaxSize()){Text("Финансовый календарь",style=MaterialTheme.typography.headlineMedium,modifier=Modifier.padding(16.dp));LazyColumn(contentPadding=PaddingValues(horizontal=16.dp)){items(ev){x->CalendarEventBlock(x)}}}}
@Composable fun CalendarEventBlock(e:CalendarEvent){val bg=if(e.income)IncomeContainer else ExpenseContainer;val fg=if(e.income)IncomeColor else ExpenseColor;Card(colors=CardDefaults.cardColors(bg),Modifier.fillMaxWidth().padding(vertical=4.dp)){Row(Modifier.fillMaxWidth().padding(12.dp),horizontalArrangement=Arrangement.SpaceBetween){Column{Text(formatDate(e.date));Text(e.title,color=fg)};Text("${if(e.income)"+" else "-"}${money(e.amount)}",color=fg)}}}

@Composable fun StatisticsScreen(operations:List<Operation>,accounts:List<Account>,modifier:Modifier=Modifier){var period by remember{mutableStateOf("Текущий месяц")};var cs by remember{mutableStateOf("")};var ce by remember{mutableStateOf("")};val (start,end)=when(period){"Предыдущий месяц"->{val a=Calendar.getInstance().apply{set(Calendar.DAY_OF_MONTH,1);add(Calendar.MONTH,-1);set(Calendar.HOUR_OF_DAY,0);set(Calendar.MINUTE,0);set(Calendar.SECOND,0);set(Calendar.MILLISECOND,0)};val b=Calendar.getInstance().apply{set(Calendar.DAY_OF_MONTH,1);set(Calendar.HOUR_OF_DAY,0);set(Calendar.MINUTE,0);set(Calendar.SECOND,0);set(Calendar.MILLISECOND,0);timeInMillis-=1};a.timeInMillis to b.timeInMillis};"Год"->{val a=Calendar.getInstance().apply{set(Calendar.DAY_OF_YEAR,1);set(Calendar.HOUR_OF_DAY,0);set(Calendar.MINUTE,0);set(Calendar.SECOND,0);set(Calendar.MILLISECOND,0)};a.timeInMillis to System.currentTimeMillis()};"Произвольные даты"->{val a=parseDate(cs);val b=parseDate(ce);if(a!=null&&b!=null)a to b+86399999 else 0L to 0L};else->{val a=Calendar.getInstance().apply{set(Calendar.DAY_OF_MONTH,1);set(Calendar.HOUR_OF_DAY,0);set(Calendar.MINUTE,0);set(Calendar.SECOND,0);set(Calendar.MILLISECOND,0)};a.timeInMillis to System.currentTimeMillis()}};val po=operations.filter{it.id in start..end};val inc=po.filter{it.income};val ex=po.filter{!it.income};val man=ex.filter{it.mandatory};val non=ex.filter{!it.mandatory};val it=inc.sumOf{it.amount};val mt=man.sumOf{it.amount};val nt=non.sumOf{it.amount};val et=ex.sumOf{it.amount};val days=(((end-start)/86400000)+1).coerceAtLeast(1);val d=et/days;val w=d*7;val m=d*30.4375;Column(modifier.fillMaxSize().verticalScroll(rememberScrollState()).padding(16.dp)){Text("Статистика",style=MaterialTheme.typography.headlineMedium);Spacer(Modifier.height(12.dp));listOf("Текущий месяц","Предыдущий месяц","Год","Произвольные даты").forEach{x->FilterChip(period==x,{period=x},label={Text(x)});Spacer(Modifier.height(4.dp))};if(period=="Произвольные даты"){OutlinedTextField(cs,{cs=it},label={Text("Начало ДД.ММ.ГГГГ")},Modifier.fillMaxWidth());OutlinedTextField(ce,{ce=it},label={Text("Конец ДД.ММ.ГГГГ")},Modifier.fillMaxWidth())};StatCard("Доходы",it,IncomeContainer,IncomeColor);StatCard("Обязательные расходы",mt,ExpenseContainer,ExpenseColor);StatCard("Необязательные расходы",nt,ExpenseContainer,ExpenseColor);StatCard("Все расходы",et,ExpenseContainer,ExpenseColor);AverageExpenseCard(d,w,m);Text("Остатки по счетам",style=MaterialTheme.typography.titleLarge);val bs=balances(accounts,operations);accounts.forEach{x->Text("${x.name}: ${money(bs[x.id]?:0.0)}")};Text("Остаток за период: ${money(it-et)}")}}
@Composable fun StatCard(title:String,value:Double,bg:Color,fg:Color){Card(colors=CardDefaults.cardColors(bg),Modifier.fillMaxWidth().padding(vertical=4.dp)){Column(Modifier.padding(16.dp)){Text(title,color=fg);Text(money(value),style=MaterialTheme.typography.titleLarge,color=fg)}}}
@Composable fun AverageExpenseCard(daily:Double,weekly:Double,monthly:Double){Card(Modifier.fillMaxWidth().padding(vertical=8.dp)){Column(Modifier.padding(16.dp)){Text("Средние расходы",style=MaterialTheme.typography.titleLarge);ExpenseComparisonRow("День",daily,weekly,monthly);ExpenseComparisonRow("Неделя",daily,weekly,monthly);ExpenseComparisonRow("Месяц",daily,weekly,monthly)}}}
@Composable fun ExpenseComparisonRow(label:String,day:Double,week:Double,month:Double){Row(Modifier.fillMaxWidth().padding(vertical=4.dp),horizontalArrangement=Arrangement.SpaceBetween){Text(label);Text("День ${money(day)} / Нед ${money(week)} / Мес ${money(month)}",color=ExpenseColor)}}

@Composable fun MoreScreen(forecast:List<ForecastItem>,accounts:List<Account>,onForecastChange:(List<ForecastItem>)->Unit,onOperationAdded:(Operation)->Unit,modifier:Modifier=Modifier){var add by remember{mutableStateOf(false)};Column(modifier.fillMaxSize().verticalScroll(rememberScrollState()).padding(16.dp)){Text("Ещё",style=MaterialTheme.typography.headlineMedium);Button({add=true},Modifier.fillMaxWidth()){Text("Добавить операцию")};Spacer(Modifier.height(8.dp));ForecastSummary(forecast,accounts);forecast.sortedBy{it.date}.forEach{x->val bg=if(x.income)IncomeContainer else ExpenseContainer;val fg=if(x.income)IncomeColor else ExpenseColor;Card(colors=CardDefaults.cardColors(bg),Modifier.fillMaxWidth().padding(vertical=4.dp)){Row(Modifier.fillMaxWidth().padding(12.dp),horizontalArrangement=Arrangement.SpaceBetween){Column{Text(x.name,color=fg);Text(formatDate(x.date));Text(x.recurrence)};Text("${if(x.income)"+" else "-"}${money(x.amount)}",color=fg)}}}};if(add)AddOperationDialog(accounts,{add=false},{onOperationAdded(it);add=false})}}
@Composable fun ForecastSummary(forecast:List<ForecastItem>,accounts:List<Account>){val t=System.currentTimeMillis();val items=forecast.filter{it.date in t..t+90L*86400000};val i=items.filter{it.income}.sumOf{it.amount};val e=items.filter{!it.income}.sumOf{it.amount};Text("Прогноз на 90 дней",style=MaterialTheme.typography.titleLarge);SummaryBlock("Будущие доходы",i,IncomeContainer,IncomeColor);SummaryBlock("Будущие расходы",e,ExpenseContainer,ExpenseColor);Text("Прогнозируемый баланс: ${money(balances(accounts,emptyList()).values.sum()+i-e)}")}

@Composable fun AddOperationDialog(accounts:List<Account>,onDismiss:()->Unit,onSave:(Operation)->Unit){var amount by remember{mutableStateOf("")};var category by remember{mutableStateOf("")};var comment by remember{mutableStateOf("")};var income by remember{mutableStateOf(false)};var mandatory by remember{mutableStateOf(false)};var accountId by remember{mutableStateOf(accounts.firstOrNull()?.id?:0L)};AlertDialog(onDismissRequest=onDismiss,title={Text("Новая операция")},text={Column(Modifier.verticalScroll(rememberScrollState())){OutlinedTextField(amount,{amount=it},label={Text("Сумма")});Row{FilterChip(income,{income=true},label={Text("Доход")});Spacer(Modifier.width(8.dp));FilterChip(!income,{income=false},label={Text("Расход")})};if(!income){Row{FilterChip(mandatory,{mandatory=true},label={Text("Обязательный")});Spacer(Modifier.width(8.dp));FilterChip(!mandatory,{mandatory=false},label={Text("Необязательный")})}};OutlinedTextField(category,{category=it},label={Text("Категория")});OutlinedTextField(comment,{comment=it},label={Text("Комментарий")});AccountSelector("Счёт",accounts,accountId){accountId=it}}},confirmButton={TextButton({val v=amount.replace(',','.').toDoubleOrNull();if(v!=null&&v>0&&category.isNotBlank()&&accountId!=0L)onSave(Operation(System.currentTimeMillis(),v,category,comment,income,accountId,!income&&mandatory))}){Text("Сохранить")}},dismissButton={TextButton(onDismiss){Text("Отмена")}})}
@Composable fun AccountSelector(title:String,accounts:List<Account>,selectedId:Long,onSelected:(Long)->Unit){var ex by remember{mutableStateOf(false)};Box{OutlinedButton({ex=true},Modifier.fillMaxWidth()){Text("$title: ${accounts.firstOrNull{it.id==selectedId}?.name?:"Не выбран"}")};DropdownMenu(ex,{ex=false}){accounts.forEach{a->DropdownMenuItem({Text(a.name)},{onSelected(a.id);ex=false})}}}}
